apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-ei8g
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0035-tenant/tkrw-pr712-0075-0035-app/devfile-sample-ei8g@sha256:53898ae2f83a98b9b5688a5b7ff3c0c94738b293c17f1422c17501c61045f076
        name: my-nodejs
        resources: {}
status: {}
